#!/bin/bash
# cron-failsafe.sh — Defense-in-depth for critical scheduled tasks
# Inspired by Arkasha's Moltbook post on OpenClaw cron regression
# Kit 🦊 2026-02-07

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FAILSAFE_DIR="${SCRIPT_DIR}/../memory/failsafe-jobs"

usage() {
  cat <<USAGE
Usage: $0 <command> [args]

Commands:
  add <name> <cron_expr> <webhook_url> <message> [fallback_cmd]
    Register a failsafe job with optional direct fallback command

  list
    Show all registered failsafe jobs

  install
    Generate system crontab entries for all jobs (with fallback chains)

  test <name>
    Dry-run a specific job's fallback chain

  check
    Verify OpenClaw cron health (are scheduled jobs actually firing?)

Design:
  Layer 1: OpenClaw cron (may fail — known regression in 2026.2.3+)
  Layer 2: System crontab → OpenClaw webhook (fails if Gateway down)
  Layer 3: Direct command fallback (e.g., Telegram API, email, etc.)

  Each layer only fires if the previous one didn't succeed.
USAGE
}

cmd_add() {
  local name="$1" cron="$2" webhook="$3" message="$4" fallback="${5:-}"
  mkdir -p "$FAILSAFE_DIR"
  
  cat > "$FAILSAFE_DIR/$name.json" << JOBEOF
{
  "name": "$name",
  "cron": "$cron",
  "webhook": "$webhook",
  "message": "$message",
  "fallback": "$fallback",
  "created": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
JOBEOF
  echo "✅ Job '$name' registered"
}

cmd_list() {
  if [ ! -d "$FAILSAFE_DIR" ] || [ -z "$(ls "$FAILSAFE_DIR"/*.json 2>/dev/null)" ]; then
    echo "No failsafe jobs registered."
    return
  fi
  
  printf "%-20s %-15s %s\n" "NAME" "SCHEDULE" "MESSAGE"
  printf "%-20s %-15s %s\n" "----" "--------" "-------"
  for f in "$FAILSAFE_DIR"/*.json; do
    name=$(jq -r '.name' "$f")
    cron=$(jq -r '.cron' "$f")
    msg=$(jq -r '.message[0:50]' "$f")
    printf "%-20s %-15s %s\n" "$name" "$cron" "$msg"
  done
}

cmd_install() {
  if [ ! -d "$FAILSAFE_DIR" ] || [ -z "$(ls "$FAILSAFE_DIR"/*.json 2>/dev/null)" ]; then
    echo "No jobs to install."
    return
  fi
  
  echo "# Generated by cron-failsafe.sh — $(date -u)"
  echo "# Layer 2+3: system cron with webhook + direct fallback"
  echo ""
  
  for f in "$FAILSAFE_DIR"/*.json; do
    name=$(jq -r '.name' "$f")
    cron=$(jq -r '.cron' "$f")
    webhook=$(jq -r '.webhook' "$f")
    message=$(jq -r '.message' "$f")
    fallback=$(jq -r '.fallback // empty' "$f")
    
    echo "# Job: $name"
    if [ -n "$fallback" ]; then
      echo "$cron curl -sf \"$webhook\" -d '{\"text\":\"$message\",\"mode\":\"now\"}' >/dev/null 2>&1 || $fallback"
    else
      echo "$cron curl -sf \"$webhook\" -d '{\"text\":\"$message\",\"mode\":\"now\"}' >/dev/null 2>&1"
    fi
    echo ""
  done
}

cmd_test() {
  local name="$1"
  local f="$FAILSAFE_DIR/$name.json"
  [ ! -f "$f" ] && echo "Job '$name' not found" && exit 1
  
  echo "Testing failsafe chain for: $name"
  echo ""
  
  webhook=$(jq -r '.webhook' "$f")
  fallback=$(jq -r '.fallback // empty' "$f")
  
  echo "Layer 1: OpenClaw cron (not testable from here)"
  echo "Layer 2: Webhook → $webhook"
  echo -n "  Testing... "
  if curl -sf --max-time 5 "$webhook" >/dev/null 2>&1; then
    echo "✅ reachable"
  else
    echo "❌ unreachable"
  fi
  
  if [ -n "$fallback" ]; then
    echo "Layer 3: Direct fallback → $fallback"
    echo "  (dry run — not executing)"
  else
    echo "Layer 3: No fallback configured ⚠️"
  fi
}

cmd_check() {
  echo "OpenClaw Cron Health Check"
  echo "========================="
  
  # Check if gateway is running
  if pgrep -f "openclaw" >/dev/null 2>&1; then
    echo "Gateway process: ✅ running"
  else
    echo "Gateway process: ❌ not found"
  fi
  
  # Check cron jobs file
  local cron_file="$HOME/.openclaw/cron/jobs.json"
  if [ -f "$cron_file" ]; then
    local count=$(jq 'length' "$cron_file" 2>/dev/null || echo 0)
    echo "Cron jobs configured: $count"
    
    # Check for null nextRunAtMs (known bug)
    local null_next=$(jq '[.[] | select(.nextRunAtMs == null)] | length' "$cron_file" 2>/dev/null || echo "?")
    if [ "$null_next" != "0" ] && [ "$null_next" != "?" ]; then
      echo "⚠️ Jobs with null nextRunAtMs: $null_next (known bug!)"
    fi
  else
    echo "Cron jobs file: not found"
  fi
}

case "${1:-help}" in
  add) shift; cmd_add "$@" ;;
  list) cmd_list ;;
  install) cmd_install ;;
  test) shift; cmd_test "$@" ;;
  check) cmd_check ;;
  *) usage ;;
esac
