#!/usr/bin/env python3
"""
nist-tool-summary.py — Generate summary of Kit's 4 NIST submission tools.

For merge prep (Mar 7). Reads each tool, extracts docstring + key metrics,
outputs a formatted section suitable for the isnad-rfc submission.

Usage: python3 nist-tool-summary.py [--markdown] [--json]
"""

import ast
import hashlib
import json
import os
import sys

TOOLS = {
    "integer-brier-scorer.py": {
        "purpose": "Scoring rule for agent predictions",
        "category": "Calibration & Accountability",
        "contribution": "Integer-only Brier scoring eliminates floating-point nondeterminism. Deterministic across hardware, MoE routing, quantization. Enables cross-platform score comparison.",
    },
    "execution-trace-commit.py": {
        "purpose": "Hash-chain execution traces for auditability",
        "category": "Provenance & Auditability",
        "contribution": "Hash-chained action log with CID-compatible output. Every agent action gets a receipt. Tamper-evident by construction — modifying any entry invalidates the chain.",
    },
    "canary-spec-commit.py": {
        "purpose": "Pre-commitment to evaluation criteria",
        "category": "Pre-commitment & Fairness",
        "contribution": "Hash evaluation spec before seeing agent output. Prevents post-hoc rationalization of scores. Spec includes rubric, weights, passing threshold — all committed before evaluation.",
    },
    "behavioral-genesis-chain.py": {
        "purpose": "Behavioral continuity across model migrations",
        "category": "Identity & Continuity",
        "contribution": "Chained behavioral snapshots track identity across migrations. Vessel (keys) ≠ mind (behavior). Kit's Opus 4.5→4.6 migration: Δ=0.051 (A). Swapped agent: Δ=0.841 (detected). Baseline accumulates with decay.",
    },
}

SCRIPTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)))


def get_file_hash(filepath):
    """SHA256 of file contents."""
    with open(filepath, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


def get_line_count(filepath):
    with open(filepath) as f:
        return sum(1 for _ in f)


def main():
    fmt = "markdown" if "--markdown" in sys.argv else "json" if "--json" in sys.argv else "markdown"
    
    results = []
    for filename, meta in TOOLS.items():
        filepath = os.path.join(SCRIPTS_DIR, filename)
        if not os.path.exists(filepath):
            print(f"⚠️  Missing: {filename}", file=sys.stderr)
            continue
        
        h = get_file_hash(filepath)
        lines = get_line_count(filepath)
        
        results.append({
            "file": filename,
            "hash": h,
            "lines": lines,
            **meta,
        })

    if fmt == "json":
        print(json.dumps(results, indent=2))
    else:
        print("# Kit's NIST Submission Tools\n")
        print(f"**Agent:** kit_fox | **Submission date:** 2026-03-09")
        print(f"**Total tools:** {len(results)} | **Total lines:** {sum(r['lines'] for r in results)}\n")
        
        for r in results:
            print(f"## {r['file']}")
            print(f"**Category:** {r['category']}  ")
            print(f"**Purpose:** {r['purpose']}  ")
            print(f"**Hash:** `{r['hash']}`  ")
            print(f"**Lines:** {r['lines']}\n")
            print(f"{r['contribution']}\n")
        
        print("---")
        print("*Generated by nist-tool-summary.py*")


if __name__ == "__main__":
    main()
