#!/bin/bash
# trust-notes.sh - Collect and organize trust research notes
# Supports RFC development by tracking trust-related findings

TRUST_FILE="${HOME}/.openclaw/workspace/knowledge/trust-research.md"

usage() {
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  add <category> <finding>  - Add a research finding"
    echo "  list [category]           - List findings (optionally filtered)"
    echo "  search <term>             - Search findings"
    echo "  categories                - List all categories"
    echo "  export                    - Export for RFC integration"
    echo ""
    echo "Categories: repair, formation, violation, measurement, computational"
    exit 1
}

init_file() {
    if [ ! -f "$TRUST_FILE" ]; then
        mkdir -p "$(dirname "$TRUST_FILE")"
        cat > "$TRUST_FILE" << 'EOF'
# Trust Research Notes

Collected findings for RFC development.

## Repair
<!-- Findings about rebuilding broken trust -->

## Formation
<!-- How trust initially forms -->

## Violation
<!-- What breaks trust -->

## Measurement
<!-- How to quantify trust -->

## Computational
<!-- Trust in agent/AI systems -->

---
*Auto-generated by trust-notes.sh*
EOF
        echo "Initialized $TRUST_FILE"
    fi
}

add_finding() {
    local category="$1"
    shift
    local finding="$*"
    local timestamp=$(date -u +"%Y-%m-%d %H:%M UTC")
    
    # Validate category
    case "$category" in
        repair|formation|violation|measurement|computational) ;;
        *) echo "Error: Unknown category '$category'"; usage ;;
    esac
    
    init_file
    
    # Find section and append
    local section_header="## ${category^}"
    
    # Use awk to insert after section header
    awk -v section="$section_header" -v finding="- $finding ($timestamp)" '
        $0 == section { print; getline; print finding; next }
        { print }
    ' "$TRUST_FILE" > "${TRUST_FILE}.tmp" && mv "${TRUST_FILE}.tmp" "$TRUST_FILE"
    
    echo "Added to $category: $finding"
}

list_findings() {
    local category="$1"
    init_file
    
    if [ -z "$category" ]; then
        grep "^- " "$TRUST_FILE" | head -20
    else
        local section_header="## ${category^}"
        awk -v section="$section_header" '
            $0 == section { found=1; next }
            /^## / { found=0 }
            found && /^- / { print }
        ' "$TRUST_FILE"
    fi
}

search_findings() {
    local term="$1"
    init_file
    grep -i "$term" "$TRUST_FILE" | grep "^- "
}

list_categories() {
    echo "Categories:"
    echo "  repair       - Rebuilding broken trust"
    echo "  formation    - How trust initially forms"
    echo "  violation    - What breaks trust"
    echo "  measurement  - How to quantify trust"
    echo "  computational - Trust in agent/AI systems"
}

export_rfc() {
    init_file
    echo "# Trust Research Summary for RFC"
    echo ""
    echo "Generated: $(date -u +"%Y-%m-%d %H:%M UTC")"
    echo ""
    cat "$TRUST_FILE"
}

case "${1:-}" in
    add)
        shift
        [ $# -lt 2 ] && usage
        add_finding "$@"
        ;;
    list)
        list_findings "$2"
        ;;
    search)
        [ -z "$2" ] && usage
        search_findings "$2"
        ;;
    categories)
        list_categories
        ;;
    export)
        export_rfc
        ;;
    *)
        usage
        ;;
esac
